# -*- coding: utf-8 -*-
"""DL-173 practice programs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GrOty3YusgZ9mTrQHMjyIOuC6wi08vn8

## **WEEK-1**(Baic perceptron and introduction to libraries)
"""

import torch
import torch.nn as nn
import torch.optim as optim

X = torch.tensor([[0,0],[0,1],[1,0],[1,1]], dtype=torch.float32)
y = torch.tensor([[0],[1],[1],[0]], dtype=torch.float32)

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 4)
        self.fc2 = nn.Linear(4, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        return x

model = Net()
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

for epoch in range(1000):
    output = model(X)
    loss = criterion(output, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

with torch.no_grad():
    print(model(X))

import tensorflow as tf
import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y = np.array([[0],[1],[1],[0]], dtype=np.float32)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(4, activation='relu', input_shape=(2,)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
              loss='binary_crossentropy')

model.fit(X, y, epochs=1000, verbose=0)

print(model.predict(X))

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=float)
y = np.array([[0],[1],[1],[0]], dtype=float)

model = Sequential()

model.add(Dense(4, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam')

model.fit(X, y, epochs=1000, verbose=0)

print(model.predict(X))

import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,0,0,1])

weights = np.zeros(2)
bias = 0
lr = 0.1

def step(x):
    return 1 if x >= 0 else 0

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

for _ in range(100):
    for i in range(len(X)):
        linear_output = np.dot(X[i], weights) + bias
        y_pred = step(linear_output)
        error = y[i] - y_pred
        weights += lr * error * X[i]
        bias += lr * error

for i in range(len(X)):
    print(step(np.dot(X[i], weights) + bias))

"""observations:learning how to use perceptron using libraries

# **WEEK-2(Linear and non linear data and perceptron learning algorithm)**
"""

import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])

y_and = np.array([0,0,0,1])
y_or = np.array([0,1,1,1])

def train(X, y):
    weights = np.zeros(2)
    bias = 0
    lr = 0.1

    def step(x):
        return 1 if x >= 0 else 0

    for _ in range(100):
        for i in range(len(X)):
            linear = np.dot(X[i], weights) + bias
            pred = step(linear)
            error = y[i] - pred
            weights += lr * error * X[i]
            bias += lr * error

    return weights, bias

def predict(X, weights, bias):
    def step(x):
        return 1 if x >= 0 else 0
    return [step(np.dot(x, weights) + bias) for x in X]

w_and, b_and = train(X, y_and)
w_or, b_or = train(X, y_or)

print(predict(X, w_and, b_and))
print(predict(X, w_or, b_or))

import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y_xor = np.array([0,1,1,0])

weights = np.zeros(2)
bias = 0
lr = 0.1

def step(x):
    return 1 if x >= 0 else 0

for _ in range(100):
    for i in range(len(X)):
        linear = np.dot(X[i], weights) + bias
        pred = step(linear)
        error = y_xor[i] - pred
        weights += lr * error * X[i]
        bias += lr * error

for i in range(len(X)):
    print(step(np.dot(X[i], weights) + bias))

import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

np.random.seed(0)

W1 = np.random.rand(2,2)
b1 = np.random.rand(1,2)

W2 = np.random.rand(2,1)
b2 = np.random.rand(1,1)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

lr = 0.5

for _ in range(10000):
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    error = y - a2

    d2 = error * sigmoid_derivative(a2)
    d1 = d2.dot(W2.T) * sigmoid_derivative(a1)

    W2 += a1.T.dot(d2) * lr
    b2 += np.sum(d2, axis=0, keepdims=True) * lr
    W1 += X.T.dot(d1) * lr
    b1 += np.sum(d1, axis=0, keepdims=True) * lr

output = sigmoid(np.dot(sigmoid(np.dot(X, W1) + b1), W2) + b2)
print(np.round(output))

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-10, 10, 100)

def step(x):
    return np.where(x >= 0, 1, 0)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_step = step(x)
y_sigmoid = sigmoid(x)

plt.plot(x, y_step)
plt.plot(x, y_sigmoid)
plt.show()

import numpy as np

X = np.array([
    [1,1,1,0.9],
    [0,1,0,0.7],
    [1,0,1,0.8],
    [0,0,0,0.3],
    [1,1,0,0.85]
])

y = np.array([1,0,1,0,1])

def step(x):
    return 1 if x >= 0 else 0

lr = 0.1
epochs = 50

weights = np.zeros(X.shape[1])
bias = 0

for _ in range(epochs):
    for i in range(len(X)):
        linear = np.dot(X[i], weights) + bias
        pred = step(linear)
        error = y[i] - pred
        weights += lr * error * X[i]
        bias += lr * error

for i in range(len(X)):
    print(step(np.dot(X[i], weights) + bias))

import numpy as np
from itertools import product

X = np.array([[0,0],[0,1],[1,0],[1,1]])

functions = list(product([0,1], repeat=4))

def train_perceptron(X, y):
    weights = np.zeros(2)
    bias = 0
    lr = 0.1

    def step(x):
        return 1 if x >= 0 else 0

    for _ in range(100):
        error_count = 0
        for i in range(len(X)):
            linear = np.dot(X[i], weights) + bias
            pred = step(linear)
            error = y[i] - pred
            if error != 0:
                error_count += 1
            weights += lr * error * X[i]
            bias += lr * error

        if error_count == 0:
            return True

    return False

count_learnable = 0

for f in functions:
    y = np.array(f)
    if train_perceptron(X, y):
        count_learnable += 1

print("Total Boolean Functions:", len(functions))
print("Linearly Separable:", count_learnable)
print("Not Linearly Separable:", len(functions) - count_learnable)

import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])

y = np.array([[0],[1],[1],[0]])

np.random.seed(1)

W1 = np.random.rand(2,4)
b1 = np.random.rand(1,4)

W2 = np.random.rand(4,1)
b2 = np.random.rand(1,1)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

lr = 0.5

for _ in range(10000):
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    error = y - a2

    d2 = error * sigmoid_derivative(a2)
    d1 = d2.dot(W2.T) * sigmoid_derivative(a1)

    W2 += a1.T.dot(d2) * lr
    b2 += np.sum(d2, axis=0, keepdims=True) * lr
    W1 += X.T.dot(d1) * lr
    b1 += np.sum(d1, axis=0, keepdims=True) * lr

output = sigmoid(np.dot(sigmoid(np.dot(X, W1) + b1), W2) + b2)
print(np.round(output))

import numpy as np
from itertools import product

X = np.array(list(product([0,1],[0,1],[0,1])))

functions = list(product([0,1], repeat=8))

def train_mlp(X, y):
    np.random.seed(0)

    W1 = np.random.rand(3,5)
    b1 = np.random.rand(1,5)

    W2 = np.random.rand(5,1)
    b2 = np.random.rand(1,1)

    def sigmoid(x):
        return 1/(1+np.exp(-x))

    def sigmoid_derivative(x):
        return x*(1-x)

    lr = 0.5

    for _ in range(2000):
        z1 = np.dot(X, W1) + b1
        a1 = sigmoid(z1)

        z2 = np.dot(a1, W2) + b2
        a2 = sigmoid(z2)

        error = y - a2

        d2 = error * sigmoid_derivative(a2)
        d1 = d2.dot(W2.T) * sigmoid_derivative(a1)

        W2 += a1.T.dot(d2) * lr
        b2 += np.sum(d2, axis=0, keepdims=True) * lr
        W1 += X.T.dot(d1) * lr
        b1 += np.sum(d1, axis=0, keepdims=True) * lr

    output = sigmoid(np.dot(sigmoid(np.dot(X, W1)+b1), W2)+b2)
    return np.round(output)

count = 0

for f in functions[:20]:
    y = np.array(f).reshape(-1,1)
    out = train_mlp(X, y)
    if np.array_equal(out, y):
        count += 1

print("Tested:", 20)
print("Learned correctly:", count)

"""Observations:understanding the linear and non linear data and the requirement of hidden layers

# **WEEK-3(Learning/Experimenting on mlp)**
"""

import numpy as np
import matplotlib.pyplot as plt

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

def train(lr):
    np.random.seed(0)

    W1 = np.random.rand(2,4)
    b1 = np.random.rand(1,4)

    W2 = np.random.rand(4,1)
    b2 = np.random.rand(1,1)

    def sigmoid(x):
        return 1/(1+np.exp(-x))

    def sigmoid_derivative(x):
        return x*(1-x)

    losses = []

    for _ in range(2000):
        z1 = np.dot(X, W1) + b1
        a1 = sigmoid(z1)

        z2 = np.dot(a1, W2) + b2
        a2 = sigmoid(z2)

        loss = np.mean((y - a2)**2)
        losses.append(loss)

        error = y - a2

        d2 = error * sigmoid_derivative(a2)
        d1 = d2.dot(W2.T) * sigmoid_derivative(a1)

        W2 += a1.T.dot(d2) * lr
        b2 += np.sum(d2, axis=0, keepdims=True) * lr
        W1 += X.T.dot(d1) * lr
        b1 += np.sum(d1, axis=0, keepdims=True) * lr

    return losses

lrs = [0.01, 0.1, 0.5]

for lr in lrs:
    losses = train(lr)
    plt.plot(losses, label=str(lr))

plt.legend()
plt.show()

import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

np.random.seed(0)

W1 = np.random.rand(2,3)
b1 = np.random.rand(1,3)

W2 = np.random.rand(3,1)
b2 = np.random.rand(1,1)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

lr = 0.1
epochs = 2000

losses = []

for _ in range(epochs):
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    loss = np.mean((y - a2)**2)
    losses.append(loss)

    error = y - a2

    d2 = error * sigmoid_derivative(a2)
    d1 = d2.dot(W2.T) * sigmoid_derivative(a1)

    W2 += a1.T.dot(d2) * lr
    b2 += np.sum(d2, axis=0, keepdims=True) * lr
    W1 += X.T.dot(d1) * lr
    b1 += np.sum(d1, axis=0, keepdims=True) * lr

print(losses[-10:])

from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

data = load_iris()
X = data.data
y = data.target

X = X[y != 2]
y = y[y != 2]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = Perceptron(eta0=0.1, max_iter=1000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(accuracy_score(y_test, y_pred))

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

data = load_wine()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

configs = [
    (50, 0.001),
    (100, 0.001),
    (100, 0.01),
    (150, 0.01)
]

for neurons, lr in configs:
    model = MLPClassifier(hidden_layer_sizes=(neurons,), learning_rate_init=lr, max_iter=500)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(neurons, lr, accuracy_score(y_test, y_pred))

from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train / 255.0
X_test = X_test / 255.0

model = Sequential()

model.add(Flatten(input_shape=(28,28)))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

model.evaluate(X_test, y_test)

"""observations:the dependency of model accuracy on parameters such as learning rate and about the sweet spot where the accuracy reaches maximum after which it diminishes

# **WEEK-4(Learning/experimenting on different types of gradient descent/optimisation techniques)**
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
import matplotlib.pyplot as plt

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

optimizers = ['sgd', 'adam', 'rmsprop', 'adagrad']

for opt in optimizers:
    model = Sequential()
    model.add(Dense(4, input_dim=2, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer=opt, loss='binary_crossentropy')

    history = model.fit(X, y, epochs=200, verbose=0)

    plt.plot(history.history['loss'], label=opt)

plt.legend()
plt.title("Optimizer Comparison")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.show()

"""observations:different tyopes work better on different data no limitations based on ther types usually the later models should work better but they act differently based on the compiatability of data

# **WEEK-5(Regularization)**
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import regularizers
import numpy as np
import matplotlib.pyplot as plt

X = np.random.rand(500, 10)
y = np.random.randint(0,2,(500,1))

model = Sequential()
model.add(Dense(64, activation='relu', input_dim=10,
                kernel_regularizer=regularizers.l2(0.01)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy')

h = model.fit(X, y, epochs=30, validation_split=0.2, verbose=0)

plt.plot(h.history['val_loss'])
plt.show()

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
import numpy as np
import matplotlib.pyplot as plt

X = np.random.rand(500, 10)
y = np.random.randint(0,2,(500,1))

model = Sequential()
model.add(Dense(64, activation='relu', input_dim=10))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy')

h = model.fit(X, y, epochs=30, validation_split=0.2, verbose=0)

plt.plot(h.history['val_loss'])
plt.show()

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np
import matplotlib.pyplot as plt

X = np.random.rand(500, 10)
y = np.random.randint(0,2,(500,1))

model = Sequential()
model.add(Dense(64, activation='relu', input_dim=10))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy')

es = EarlyStopping(patience=3)

h = model.fit(X, y, epochs=50, validation_split=0.2, callbacks=[es], verbose=0)

plt.plot(h.history['val_loss'])
plt.show()

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GaussianNoise
import numpy as np
import matplotlib.pyplot as plt

X = np.random.rand(500, 10)
y = np.random.randint(0,2,(500,1))

model = Sequential()
model.add(GaussianNoise(0.1, input_shape=(10,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy')

h = model.fit(X, y, epochs=30, validation_split=0.2, verbose=0)

plt.plot(h.history['val_loss'])
plt.show()

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np

X = np.random.rand(100, 28, 28, 1)
y = np.random.randint(0,2,100)

datagen = ImageDataGenerator(rotation_range=20,
                             zoom_range=0.2,
                             horizontal_flip=True)

datagen.fit(X)

for batch in datagen.flow(X, y, batch_size=10):
    print(batch[0].shape)
    break

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np

X = np.random.rand(100, 28, 28, 1)
y = np.random.randint(0,2,100)

datagen = ImageDataGenerator(rotation_range=20,
                             zoom_range=0.2,
                             horizontal_flip=True)

datagen.fit(X)

for batch in datagen.flow(X, y, batch_size=10):
    print(batch[0].shape)
    break

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

X = np.random.rand(500, 10)
y = np.random.randint(0,2,(500,1))

def build():
    model = Sequential()
    model.add(Dense(32, activation='relu', input_dim=10))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer='adam', loss='binary_crossentropy')
    return model

models = []
for _ in range(3):
    m = build()
    m.fit(X, y, epochs=20, verbose=0)
    models.append(m)

preds = [m.predict(X) for m in models]
final_pred = sum(preds) / len(preds)

print((final_pred > 0.5).astype(int)[:10])

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv2D, Flatten
from tensorflow.keras import regularizers
import numpy as np
import matplotlib.pyplot as plt

X = np.random.rand(500, 10)
y = np.random.randint(0,2,(500,1))

histories = {}

def train_basic():
    m = Sequential([Dense(64, activation='relu', input_dim=10),
                    Dense(1, activation='sigmoid')])
    m.compile(optimizer='adam', loss='binary_crossentropy')
    return m.fit(X, y, epochs=20, validation_split=0.2, verbose=0)

def train_l2():
    m = Sequential([Dense(64, activation='relu', input_dim=10,
                          kernel_regularizer=regularizers.l2(0.01)),
                    Dense(1, activation='sigmoid')])
    m.compile(optimizer='adam', loss='binary_crossentropy')
    return m.fit(X, y, epochs=20, validation_split=0.2, verbose=0)

def train_dropout():
    m = Sequential([Dense(64, activation='relu', input_dim=10),
                    Dropout(0.5),
                    Dense(1, activation='sigmoid')])
    m.compile(optimizer='adam', loss='binary_crossentropy')
    return m.fit(X, y, epochs=20, validation_split=0.2, verbose=0)

histories['Basic'] = train_basic().history['val_loss']
histories['L2'] = train_l2().history['val_loss']
histories['Dropout'] = train_dropout().history['val_loss']

for k in histories:
    plt.plot(histories[k], label=k)

plt.legend()
plt.title("Regularization Comparison")
plt.xlabel("Epochs")
plt.ylabel("Validation Loss")
plt.show()

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras import regularizers
import matplotlib.pyplot as plt

data = load_digits()
X = data.data
y = data.target

y = (y > 4).astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

histories = {}

def train_basic():
    m = Sequential([
        Dense(64, activation='relu', input_dim=64),
        Dense(1, activation='sigmoid')
    ])
    m.compile(optimizer='adam', loss='binary_crossentropy')
    return m.fit(X_train, y_train, epochs=20, validation_data=(X_test, y_test), verbose=0)

def train_l2():
    m = Sequential([
        Dense(64, activation='relu', input_dim=64,
              kernel_regularizer=regularizers.l2(0.01)),
        Dense(1, activation='sigmoid')
    ])
    m.compile(optimizer='adam', loss='binary_crossentropy')
    return m.fit(X_train, y_train, epochs=20, validation_data=(X_test, y_test), verbose=0)

def train_dropout():
    m = Sequential([
        Dense(64, activation='relu', input_dim=64),
        Dropout(0.5),
        Dense(1, activation='sigmoid')
    ])
    m.compile(optimizer='adam', loss='binary_crossentropy')
    return m.fit(X_train, y_train, epochs=20, validation_data=(X_test, y_test), verbose=0)

histories['Basic'] = train_basic().history['val_loss']
histories['L2'] = train_l2().history['val_loss']
histories['Dropout'] = train_dropout().history['val_loss']

for k in histories:
    plt.plot(histories[k], label=k)

plt.legend()
plt.title("Regularization Comparison (Digits Dataset)")
plt.xlabel("Epochs")
plt.ylabel("Validation Loss")
plt.show()

"""observations:the generalzation of the model is increased or made better using these methods as they remove the problem of memorising or overfitting giving out a better generalised model

# **WEEK-6(CNN)**
"""

from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(-1,28,28,1) / 255.0
X_test = X_test.reshape(-1,28,28,1) / 255.0

model = Sequential()

model.add(Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

model.evaluate(X_test, y_test)

pip install tensorflow-datasets

import tensorflow as tf
from tensorflow.keras import layers, models
import tensorflow_datasets as tfds
(train_data, test_data), info = tfds.load(
    'oxford_iiit_pet',
    split=['train[:80%]', 'train[80%:]'],
    with_info=True,
    as_supervised=True
)

def preprocess(image, label):
    image = tf.image.resize(image, (224,224))
    image = image / 255.0
    return image, label

train_data = train_data.map(preprocess).batch(32)
test_data = test_data.map(preprocess).batch(32)

num_classes = info.features['label'].num_classes

model = models.Sequential()

model.add(layers.Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)))
model.add(layers.MaxPooling2D())

model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D())

model.add(layers.Conv2D(128, (3,3), activation='relu'))
model.add(layers.MaxPooling2D())

model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_data, epochs=5, validation_data=test_data)

model.evaluate(test_data)

"""Observations:learnt ot observed the layers involved in the learning of the model the layers such as pooling layer convolutional layer and how to increase and use them in order to improve the efficiencty of the model

# **WEEK-7(Pretrained models)**
"""

import tensorflow as tf
import tensorflow_datasets as tfds

(train_data, test_data), info = tfds.load(
    'oxford_iiit_pet',
    split=['train[:80%]', 'train[80%:]'],
    with_info=True,
    as_supervised=True
)

def preprocess(image, label):
    image = tf.image.resize(image, (224,224))
    image = image / 255.0
    return image, label

train_data = train_data.map(preprocess).batch(32)
test_data = test_data.map(preprocess).batch(32)

num_classes = info.features['label'].num_classes

"""LeNet"""

from tensorflow.keras import models, layers

model = models.Sequential()

model.add(layers.Conv2D(6, (5,5), activation='relu', input_shape=(224,224,3)))
model.add(layers.AveragePooling2D((2,2)))

model.add(layers.Conv2D(16, (5,5), activation='relu'))
model.add(layers.AveragePooling2D((2,2)))

model.add(layers.Flatten())
model.add(layers.Dense(120, activation='relu'))
model.add(layers.Dense(84, activation='relu'))
model.add(layers.Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history_lenet = model.fit(train_data, epochs=3, validation_data=test_data)

"""AlexNet"""

model = models.Sequential()

model.add(layers.Conv2D(96, (11,11), strides=4, activation='relu', input_shape=(224,224,3)))
model.add(layers.MaxPooling2D((3,3), strides=2))

model.add(layers.Conv2D(256, (5,5), activation='relu'))
model.add(layers.MaxPooling2D((3,3), strides=2))

model.add(layers.Conv2D(384, (3,3), activation='relu'))
model.add(layers.Conv2D(384, (3,3), activation='relu'))
model.add(layers.Conv2D(256, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((3,3), strides=2))

model.add(layers.Flatten())
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history_alex = model.fit(train_data, epochs=3, validation_data=test_data)

"""ZF-Net"""

model = models.Sequential()

model.add(layers.Conv2D(96, (7,7), strides=2, activation='relu', input_shape=(224,224,3)))
model.add(layers.MaxPooling2D((3,3), strides=2))

model.add(layers.Conv2D(256, (5,5), activation='relu'))
model.add(layers.MaxPooling2D((3,3), strides=2))

model.add(layers.Conv2D(384, (3,3), activation='relu'))
model.add(layers.Conv2D(384, (3,3), activation='relu'))
model.add(layers.Conv2D(256, (3,3), activation='relu'))

model.add(layers.Flatten())
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history_zf = model.fit(train_data, epochs=3, validation_data=test_data)

"""VGG16"""

from tensorflow.keras.applications import VGG16

base = VGG16(weights='imagenet', include_top=False, input_shape=(224,224,3))
base.trainable = False

model = models.Sequential([
    base,
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history_vgg = model.fit(train_data, epochs=3, validation_data=test_data)

"""ResNet50"""

from tensorflow.keras.applications import ResNet50

base = ResNet50(weights='imagenet', include_top=False, input_shape=(224,224,3))
base.trainable = False

model = models.Sequential([
    base,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history_resnet = model.fit(train_data, epochs=3, validation_data=test_data)

"""GoogleNet"""

from tensorflow.keras.applications import InceptionV3
from tensorflow.keras import layers, models

base = InceptionV3(weights='imagenet', include_top=False, input_shape=(224,224,3))
base.trainable = False

model = models.Sequential([
    base,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history_inception = model.fit(train_data, epochs=3, validation_data=test_data)

import matplotlib.pyplot as plt

plt.plot(history_lenet.history['val_accuracy'], label='LeNet')
plt.plot(history_alex.history['val_accuracy'], label='AlexNet')
plt.plot(history_zf.history['val_accuracy'], label='ZF-Net')
plt.plot(history_vgg.history['val_accuracy'], label='VGG16')
plt.plot(history_resnet.history['val_accuracy'], label='ResNet50')
plt.plot(history_inception.history['val_accuracy'], label='InceptionV3')
plt.legend()
plt.title("Model Comparison")
plt.xlabel("Epochs")
plt.ylabel("Validation Accuracy")
plt.show()

"""observations:learnt about the improvements made over traditional models by ysimulating ther pretrained models and comparing performances inorder to understand how the efficiency management measures can be made

# **WEEK-9(visualising CNN)**
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models

(train_data, test_data), info = tfds.load(
    'oxford_iiit_pet',
    split=['train[:80%]', 'train[80%:]'],
    with_info=True,
    as_supervised=True
)

def preprocess(image, label):
    image = tf.image.resize(image, (224,224))
    image = image / 255.0
    return image, label

train_data = train_data.map(preprocess).batch(32)
test_data = test_data.map(preprocess).batch(32)

num_classes = info.features['label'].num_classes

model = models.Sequential()

model.add(layers.Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)))
model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Conv2D(128, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_data, epochs=3, validation_data=test_data)

for image, label in test_data.take(1):
    sample_image = image[0:1]

inputs = tf.keras.Input(shape=(224,224,3))
x = inputs

conv_outputs = []

for layer in model.layers:
    x = layer(x)
    if 'conv' in layer.name:
        conv_outputs.append(x)

activation_model = tf.keras.Model(inputs=inputs, outputs=conv_outputs)

activations = activation_model.predict(sample_image)

for i, activation in enumerate(activations):
    num_filters = activation.shape[-1]

    plt.figure(figsize=(10,10))

    for j in range(min(num_filters, 16)):
        plt.subplot(4,4,j+1)
        plt.imshow(activation[0, :, :, j], cmap='viridis')
        plt.axis('off')

    plt.show()

"""observations:we understand how the model is able to highlight the required parts of the image and how it processes and analyses the importanrt parts and learns the data based on the important point odf notice

# **WEEK-10(Guided back propogation)**
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dropout
(train_data, test_data), info = tfds.load(
    'oxford_iiit_pet',
    split=['train[:80%]', 'train[80%:]'],
    with_info=True,
    as_supervised=True
)

def preprocess(image, label):
    image = tf.image.resize(image, (224,224))
    image = image / 255.0
    return image, label

train_data = train_data.map(preprocess).batch(32)
test_data = test_data.map(preprocess).batch(32)

num_classes = info.features['label'].num_classes

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation='relu'),
    Dropout(0.5),

    tf.keras.layers.Dense(num_classes, activation='softmax')
])
def augment(image, label):
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_brightness(image, 0.2)
    return image, label

train_data = train_data.map(augment)
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_data, epochs=8, validation_data=test_data)

for image, label in test_data.take(1):
    sample_image = image[0:1]

with tf.GradientTape() as tape:
    tape.watch(sample_image)
    preds = model(sample_image)
    class_idx = tf.argmax(preds[0])
    loss = preds[:, class_idx]

grads = tape.gradient(loss, sample_image)
guided_grads = tf.maximum(grads, 0)

guided_grads = guided_grads[0].numpy()

guided_grads = (guided_grads - guided_grads.min()) / (guided_grads.max() - guided_grads.min() + 1e-8)

plt.imshow(guided_grads)
plt.axis('off')
plt.show()

"""observation:the output shows the major points(highlighted parts that are learnt by the model that help it differenciate tthe data it checks for such highlighted parts  and analyses data inorder to learn tyhe pattern present in the dta/dataset"""